### ISSUE TITLE
PHP: 8.0 Compatibility Progress

### ISSUE THREAD

**Issue by WalterWoshid** [WalterWoshid/goaop-framework#1]
I am currently working on upgrading this library to be compatible with PHP 8.0 and 8.1. Since they introduced [Attributes in PHP](https://php.watch/articles/php-attributes) and thus deprecated the [Doctrine Annotations](https://www.doctrine-project.org/projects/doctrine-annotations/en/1.13/index.html#deprecation-notice), it is required to migrate to PHP attributes.

I am probably done with the update in less than a month, maybe even less than 2 weeks hopefully.

See [Fork-branch](https://github.com/WalterWoshid/goaop-framework/tree/fork)

# Changes

<details>
  <summary>Click to show</summary>

## Kernel

The kernel now looks like this:
```php
<?php

namespace App\Aspect;

use App\Aspect\Aspects\ResponseAppender;
use Go\Core\AspectKernel;

class Kernel extends AspectKernel
{
    /**
     * # The application's aspects.
     *
     * These aspects will be applied to the application.
     *
     * Aspects should be marked with the {@link \Go\Lang\Attribute\Aspect #[Aspect]} attribute.
     *
     * @var array<int, class-string|string>
     */
    protected array $aspects = [
        ResponseAppender::class,
    ];
}
```

## Aspects

Aspects now look like this:
```php
<?php

namespace App\Aspect\Aspects;

use Go\Aop\Intercept\MethodInvocation;
use Go\Lang\Attribute\Aspect;
use Go\Lang\Attribute\Before;
use Go\Lang\Attribute\Execution;
use Inertia\ResponseFactory;

#[Aspect]
class ResponseAppender
{
    #[Before]
    #[Execution(
        public: true,
        class: ResponseFactory::class,
        method: 'render',
    )]
    public function beforeMethodExecution(MethodInvocation $invocation): void
    {
        $invocation->setArguments(['Hello new world!']);
    }
}
```

## Bootstrapping

The bootstrapping/initialization now looks like this:
```php
<?php

use App\Aspect\Kernel;

// Add AOP library
Kernel::init(
    debug:    true,
    appDir:   __DIR__ . '/..',
    cacheDir: __DIR__ . '/../storage/aop',
    includePaths: [
        __DIR__ . '/../vendor/inertiajs/inertia-laravel/src',
        __DIR__ . '/../app',
    ]
);
```

</details>

# Progress

- [ ] Replace the deprecated Doctrine Annotations with PHP attributes - https://github.com/WalterWoshid/goaop-framework/issues/2
  - [ ] After
    - [X] Initialization/Usage
    - [ ] Parsing
    - [X] PhpDoc Documentation
  - [ ] AfterThrowing
    - [X] Initialization/Usage
    - [ ] Parsing
    - [ ] PhpDoc Documentation
  - [ ] And
    - [X] Initialization/Usage
    - [ ] Parsing
    - [ ] PhpDoc Documentation
  - [ ] Around
    - [X] Initialization/Usage
    - [ ] Parsing
    - [ ] PhpDoc Documentation
  - [X] Aspect
    - [X] Initialization/Usage
    - [X] Parsing
    - [X] PhpDoc Documentation
  - [ ] Before
    - [X] Initialization/Usage
    - [ ] Parsing
    - [X] PhpDoc Documentation
  - [ ] DeclareError
    - [X] Initialization/Usage
    - [ ] Parsing
    - [X] PhpDoc Documentation
  - [ ] DeclareParents
    - [X] Initialization/Usage
    - [ ] Parsing
    - [ ] PhpDoc Documentation
  - [ ] Execution
    - [X] Initialization/Usage
    - [ ] Parsing
    - [X] PhpDoc Documentation
  - [ ] Not
    - [X] Initialization/Usage
    - [ ] Parsing
    - [ ] PhpDoc Documentation
  - [ ] Or
    - [X] Initialization/Usage
    - [ ] Parsing
    - [ ] PhpDoc Documentation
  - [ ] Pointcut
    - [X] Initialization/Usage
    - [ ] Parsing
    - [X] PhpDoc Documentation
- [X] Refactor Container services with the [Singleton Pattern](https://designpatternsphp.readthedocs.io/de/latest/Creational/Singleton/README.html)
- [x] Add [JetBrains/phpstorm-attributes](https://github.com/JetBrains/phpstorm-attributes) for better completions
- [X] Remove [goaop-parser-reflection](https://github.com/goaop/parser-reflection) and replace with [BetterReflection](https://github.com/Roave/BetterReflection)
- [X] Update Copyright comments
- [X] Replace [Doctrine Cache](https://www.doctrine-project.org/projects/doctrine-orm/en/2.4/reference/caching.html) with [Symfony Cache](https://symfony.com/doc/current/components/cache.html)
- [ ] Improve overall code documentation
- [ ] Edit README files - https://github.com/WalterWoshid/goaop-framework/issues/3
- [ ] Faster parsing and rebuilding of source code and ast-tree (It was fast before, I didn't notice that modifying the current method was a bad decision
- [ ] Rewrite tests - https://github.com/WalterWoshid/goaop-framework/issues/4

**Comment by WalterWoshid** [comment]
Commits are coming in any minute now

**Comment by WalterWoshid** [comment]
https://github.com/goaop/framework/pull/486

**Comment by lisachenko** [comment]
@WalterWoshid really happy that you decided to work on PHP8 support 🎁  and https://github.com/goaop/framework/pull/486, this makes me happy )) 

Wish you good luck and best wishes on this way!

**Comment by lisachenko** [comment]
BTW, have you succeeded with integration of BetterReflection with goaop? I have spent few hours trying to switch to BR instead of `goaop/parser-reflection` but without any success.

On a long run - this will be logical step to switch from own parsing library (which requires maintenance) to BR, which is now used in many places, including phpstan, for example.

**Comment by WalterWoshid** [comment]
> @WalterWoshid really happy that you decided to work on PHP8 support 🎁 and [goaop#486](https://github.com/goaop/framework/pull/486), this makes me happy ))

I really love aspect oriented programming! And this is a great library :)

**Comment by WalterWoshid** [comment]
> BTW, have you succeeded with integration of BetterReflection with goaop?

I had some difficulties with locating source files, but I think I was very close on `fork-2` or `fork-3` with implementing it. Once done with attribute support for `goaop/parser-reflection` I will implement BetterReflection!
